from fpdf import FPDF
from arabic_reshaper import reshape
from bidi.algorithm import get_display
from datetime import datetime, timedelta
today = datetime.now()
today_4y = datetime.now()+ timedelta(days=1461)

# Menggunakan method strftime() untuk mengubah format tanggal
date_string = today.strftime("%d %B %Y")
date_string_4y = today_4y.strftime("%d %B %Y") 
class PDF(FPDF):
    def __init__(self):
        super().__init__()

    def row(self, data):
        for item in data:
            self.cell(40, 10, item, 1)

def generate(data:dict):
    ids = data.get('_id','-')
    product_type = data.get('product_type','-')
    product_name = data.get('product_name','-')
    company_name = data.get('name','-')
    company_address = data.get('address','-')
    product = data.get('matrix',["None"])
    pdf = FPDF()
    pdf.add_page()
    pdf.image('./app/assets/pancasila.png',90,10,30,30)
    pdf.add_font('Bookman', '', 'app/assets/font/Bookman.ttf', uni=True)
    pdf.add_font('Dejavu', '', 'app/assets/font/DejaVuSansCondensed.ttf', uni=True)
    pdf.add_font('Amiri', '', 'app/assets/font/Amiri-Regular.ttf', uni=True)
    pdf.set_font('Bookman', '', 14)
    pdf.cell(190,70,'REPUBLIK INDONESIA', border=0,ln = 1, fill=False,align='C')
    pdf.add_font('BookmanItalic', '', './app/assets/font/Bookman Italic.ttf', uni=True)
    pdf.set_font('BookmanItalic', '', 14)
    pdf.set_text_color(113, 191, 44)
    pdf.cell(190,-55,'(REPUBLIC OF INDONESIA)', ln = 1,border=0, align='C')
    pdf.set_font('Amiri', '', 14)
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(190,75,get_display(reshape(u'جمهورية إندونيسيا')), ln = 1,border=0, align='C')
    pdf.set_font('Bookman', '', 15)
    pdf.cell(190,-45,'SERTIFIKAT HALAL', border=0,ln = 1, fill=False,align='C')
    pdf.set_text_color(113, 191, 44)
    pdf.set_font('BookmanItalic', '', 14)
    pdf.cell(190,30,'( HALAL CERTIFICATE )', ln = 1,border=0, align='C')
    pdf.set_font('Amiri', '', 30)
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(190,10,get_display(reshape(u'شهادة الحلال')), ln = 1,border=0, align='C')
    data = ['Nomor Sertifikat', 'ID31110000123200921', get_display(reshape(u'رقم الشهادة'))]
    pdf.set_font('Amiri', '', 15)
    # for item in data:
    pdf.cell(70, 20, data[0], 2,0, 'C')
    pdf.set_font('Amiri', '', 20)
    pdf.cell(70, 20, data[1], 2,0, 'C')
    pdf.cell(40, 20, data[2], 2,0, 'C')
    pdf.ln()
    pdf.set_font('Amiri', '', 14)
    pdf.set_text_color(113, 191, 44)
    pdf.cell(70, -8, 'Certificate Number', 2,0, 'C')
    pdf.ln()
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(190,25,'Berdasarkan keputusan penetapan halal produk Majelis Ulama Indonesia nomor :', ln = 1,border=0, align='C')
    pdf.set_text_color(113, 191, 44)
    pdf.cell(190,-15,'Based on the decree to stipulating halal products of the Indonesian Council of Ulama ', ln = 1,border=0, align='C')
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(190,40,get_display(reshape(u'استنادا على قرار مجلس العلماء الإندونيسي عن تحديد الحلال للمنتجات')), ln = 1,border=0, align='C')
    lppom = 'LPPOM-00200128010921 Tanggal '+date_string
    pdf.cell(190,-24,lppom, ln = 1,border=0, align='C')
    # pdf.ln()
    pdf.set_font('Amiri', '', 12)
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 50, 'Jenis Produk', 2,0, 'L')
    pdf.cell(70, 50, product_type, 2,0, 'L')
    pdf.cell(70, 50, '', 2,0, 'C')
    pdf.ln()
    pdf.set_text_color(113, 191, 44)
    pdf.cell(70, -38, 'Type of Product', 2,0, 'L')
    pdf.ln()
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 50, 'Nama Produk', 2,0, 'L')
    pdf.cell(70, 50, product_name, 2,0, 'L')
    pdf.cell(70, 50, '', 2,0, 'C')
    pdf.ln()
    pdf.set_text_color(113, 191, 44)
    pdf.cell(70, -38, 'Name of Product', 2,0, 'L')
    pdf.ln()

    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 50, 'Nama Pelaku Usaha', 2,0, 'L')
    pdf.cell(70, 50, company_name, 2,0, 'L')
    pdf.cell(70, 50, '', 2,0, 'C')
    pdf.ln()
    pdf.set_text_color(113, 191, 44)
    pdf.cell(70, -38, 'Name of Company', 2,0, 'L')
    # pdf.ln()
    pdf.ln()
    pdf.cell(70, 20, '', 2,0, 'C')
    pdf.ln()

    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 10, 'Alamat Pelaku Usaha', 2,0, 'L')
    # pdf.ln()
    pdf.multi_cell(110,6, company_address,0,'L')
    pdf.set_text_color(113, 191, 44)
    pdf.ln()
    pdf.cell(70, -28, 'Company Address', 2,0, 'L')
    pdf.ln()
    pdf.cell(70, 0, ' ', 2,0,)
    pdf.ln()

    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 50, 'Diterbitkan Pada', 2,0, 'L')
    pdf.cell(70, 50, date_string, 2,0, 'L')
    pdf.cell(70, 50, '', 2,0, 'C')
    pdf.ln()
    pdf.set_text_color(113, 191, 44)
    pdf.cell(70, -40, 'Issued in ', 2,0, 'L')
    # pdf.ln()
    pdf.ln()

    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 50, 'Berlaku sampai dengan', 2,0, 'L')
    pdf.cell(70, 50, date_string_4y, 2,0, 'L')
    pdf.cell(70, 50, '', 2,0, 'C')
    pdf.ln()
    pdf.set_text_color(113, 191, 44)
    pdf.cell(70, -40, 'Valid until ', 2,0, 'L')
    # pdf.ln()
    pdf.ln()
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(190,50,'telah memenuhi ketentuan perundang-undangan', ln = 1,border=0, align='C')
    pdf.set_text_color(113, 191, 44)
    pdf.cell(190,-40,'Has complied with the provision of laws and regulations', ln = 1,border=0, align='C')
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(190,50,get_display(reshape(u'قد استوفت أحكام التشريع')), ln = 1,border=0, align='C')
    # pdf.ln()
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, -30, 'KEPALA BADAN PENYELENGGARA JAMINAN PRODUK HALAL', 2,0, 'L')
    # pdf.ln()
    pdf.cell(70,-30, '', 2,0, 'L')
    pdf.cell(70, -30, '', 2,0, 'L')
    pdf.ln()
    pdf.cell(70, 40, 'Mastuki', 2,0, 'L')
    pdf.ln()


    pdf.add_page()
    pdf.image('./app/assets/pancasila.png',90,10,30,30)
    pdf.add_font('Bookman', '', './app/assets/font/Bookman.ttf', uni=True)
    pdf.add_font('Dejavu', '', './app/assets/font/DejaVuSansCondensed.ttf', uni=True)
    pdf.add_font('Amiri', '', './app/assets/font/Amiri-Regular.ttf', uni=True)
    pdf.set_font('Bookman', '', 14)
    pdf.cell(190,70,'REPUBLIK INDONESIA', border=0,ln = 1, fill=False,align='C')
    pdf.add_font('BookmanItalic', '', './app/assets/font/Bookman Italic.ttf', uni=True)
    pdf.set_font('BookmanItalic', '', 14)
    pdf.set_text_color(113, 191, 44)
    pdf.cell(190,-55,'(REPUBLIC OF INDONESIA)', ln = 1,border=0, align='C')
    pdf.set_font('Amiri', '', 14)
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(190,75,get_display(reshape(u'جمهورية إندونيسيا')), ln = 1,border=0, align='C')
    pdf.set_font('Bookman', '', 15)
    pdf.cell(190,-45,'LAMPIRAN SERTIFIKAT HALAL', border=0,ln = 1, fill=False,align='C')
    pdf.set_text_color(113, 191, 44)
    pdf.set_font('BookmanItalic', '', 14)
    pdf.cell(190,30,'(THE ATTACHMENT OF  HALAL CERTIFICATE )', ln = 1,border=0, align='C')
    pdf.set_font('Amiri', '', 30)
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(190,10,get_display(reshape(u'مرفقة لشهادة الحلال')), ln = 1,border=0, align='C')
    data = ['Nomor Sertifikat', 'ID31110000123200921', get_display(reshape(u'رقم الشهادة'))]
    pdf.set_font('Amiri', '', 15)
    data = ['Nomor Sertifikat', 'ID31110000123200921', get_display(reshape(u'رقم الشهادة'))]
    pdf.set_font('Amiri', '', 15)
    # for item in data:
    pdf.cell(70, 20, data[0], 2,0, 'C')
    pdf.set_font('Amiri', '', 12)
    pdf.cell(70, 20, data[1], 2,0, 'C')
    pdf.cell(30, 20, data[2], 2,0, 'R')
    pdf.ln()

    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 20, 'Nama Pelaku Usaha', 2,0, 'L')
    pdf.cell(70, 20, company_name, 2,0, 'L')
    pdf.cell(70, 20, '', 2,0, 'C')
    pdf.ln()
    pdf.set_text_color(113, 191, 44)
    pdf.cell(70, -10, 'Name of Company', 2,0, 'L')
    # pdf.ln()
    pdf.ln()
    pdf.cell(70, 3, '', 2,0, 'C')
    pdf.ln()


    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 20, 'Jenis Produk', 2,0, 'L')
    pdf.cell(70, 20, product_type, 2,0, 'L')
    pdf.cell(70, 20, '', 2,0, 'C')
    pdf.ln()
    pdf.set_text_color(113, 191, 44)
    pdf.cell(70, -10, 'Type of Product', 2,0, 'L')
    # pdf.ln()
    pdf.ln()
    pdf.cell(70, 7, '', 2,0, 'C')
    pdf.ln()

    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 10, 'Alamat Pelaku Usaha', 2,0, 'L')
    # pdf.ln()
    pdf.multi_cell(110,6, company_address,0,'L')
    pdf.set_text_color(113, 191, 44)
    pdf.ln()
    pdf.cell(70, -28, 'Company Address', 2,0, 'L')
    pdf.ln()
    pdf.cell(70, 20, '', 2,0,)
    pdf.ln()
    num = 1
    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 10, 'Daftar Produk / Product Name', 2,1)
    pdf.cell(20, 7, 'No',1,0, 'L')
    pdf.cell(150, 7, 'Nama Produk', 1,0,"L")
    pdf.ln()
    
    for item in product:
        pdf.cell(20, 7, str(num),1,0, 'L')
        pdf.cell(150, 7, item, 1,0,"L")
        num +=1 
        pdf.ln()
    pdf.cell(70, -15, '', 2,1)

    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 50, 'Diterbitkan Pada', 2,0, 'L')
    pdf.cell(70, 50, date_string, 2,0, 'L')
    pdf.cell(70, 50, '', 2,0, 'C')
    pdf.ln()
    pdf.set_text_color(113, 191, 44)
    pdf.cell(70, -40, 'Issued in ', 2,0, 'L')
    # pdf.ln()
    pdf.ln()

    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, 50, 'Berlaku sampai dengan', 2,0, 'L')
    pdf.cell(70, 50, date_string_4y, 2,0, 'L')
    pdf.cell(70, 50, '', 2,0, 'C')
    pdf.ln()
    pdf.set_text_color(113, 191, 44)
    pdf.cell(70, -40, 'Valid until ', 2,0, 'L')
    # pdf.ln()
    pdf.ln()
    pdf.cell(70, 45, '', 2,1)

    pdf.set_text_color( 53, 53, 53)
    pdf.cell(70, -30, 'KEPALA BADAN PENYELENGGARA JAMINAN PRODUK HALAL', 2,0, 'L')
    # pdf.ln()
    pdf.cell(70,-30, '', 2,0, 'L')
    pdf.cell(70, -30, '', 2,0, 'L')
    pdf.ln()
    pdf.cell(70, 50, 'Mastuki', 2,0, 'L')
    pdf.ln()
    names = f'app/assets/certificate-{ids}.pdf'
    pdf.output(names, 'F')
    return names
